---
- name: Download spark-bench
  get_url:
    url: https://github.com/SparkTC/spark-bench/releases/download/v55/spark-bench_2.1.1_0.2.2-RELEASE_55.tgz
    dest: /usr/local/spark-bench_2.1.1_0.2.2-RELEASE.tar.gz

- name: Extract spark-bench
  unarchive:
    src: /usr/local/spark-bench_2.1.1_0.2.2-RELEASE.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Run spark-bench example
  shell: |
    export PATH=$PATH:/usr/local/java/bin
    export SPARK_HOME=/usr/local/spark
    export SPARK_MASTER_HOST=spark://{{ ansible_host }}:7077
    export SB_HOME=/usr/local/spark-bench_2.1.1_0.2.2-RELEASE
    $SB_HOME/bin/spark-bench.sh $SB_HOME/examples/minimal-example.conf
  register: spark_bench_minimal
  become_user: hadoop

- debug:
    msg: "{{ spark_bench_minimal.stdout }}"

- name: Add generate conf
  template:
    src: generate-files.conf
    dest: /usr/local/spark-bench_2.1.1_0.2.2-RELEASE/examples/generate-files.conf

- name: Add kmeans run conf
  template:
    src: kmeans.conf
    dest: /usr/local/spark-bench_2.1.1_0.2.2-RELEASE/examples/kmeans.conf

- file:
    path: /tmp/kmeans-medium/
    state: directory
    owner: hadoop
    group: hadoop

- name: Generate kmeans files
  shell: |
    export PATH=$PATH:/usr/local/java/bin
    export SPARK_HOME=/usr/local/spark
    export SPARK_MASTER_HOST=spark://{{ ansible_host }}:7077
    export SB_HOME=/usr/local/spark-bench_2.1.1_0.2.2-RELEASE
    $SB_HOME/bin/spark-bench.sh $SB_HOME/examples/generate-files.conf
  args:
    creates: /tmp/kmeans-medium/kmeans-data.csv
  become_user: hadoop
  when: spark_bench_generate_kmeans|default(true)

- name: Pull kmeans generation locally onto control host
  synchronize:
    mode: pull
    src:  /tmp/kmeans-medium/kmeans-data.csv
    dest: /tmp/kmeans-medium/
    recursive: yes
  when: spark_bench_generate_kmeans|default(true)

- name: Push kmeans from control host to remote host
  synchronize:
    src:  /tmp/kmeans-medium/
    dest: /tmp/kmeans-medium/
    recursive: yes
  when: not spark_bench_generate_kmeans|default(true)

- name: Wait to help post test graphs
  pause:
    seconds: 10

- stat:
    path: /tmp/kmeans-medium-run
  register: check_kmeans

- pause:
    prompt: "If you want to run kmeans benchmark, delete /tmp/kmeans-medium-run"
  when: check_kmeans.stat.exists == True

- name: Run kmeans benchmark
  shell: |
    export PATH=$PATH:/usr/local/java/bin
    export SPARK_HOME=/usr/local/spark
    export SPARK_MASTER_HOST=spark://{{ ansible_host }}:7077
    export SB_HOME=/usr/local/spark-bench_2.1.1_0.2.2-RELEASE
    $SB_HOME/bin/spark-bench.sh $SB_HOME/examples/kmeans.conf
  args:
    creates: /tmp/kmeans-medium-run
  register: spark_bench_kmeans
  become_user: hadoop

- debug:
    msg: "{{ spark_bench_kmeans.stdout }}"
