---
- hosts: all
  become: yes
  tasks:
    - import_tasks: users.yml

- hosts: all
  become: yes
  roles:
    - role: andrewrothstein.spark
  tasks:
    - import_tasks: setup.yml

- hosts: all
  become: yes
  roles:
    - {role: spark-bench, spark_master: "spark"}
