---
- hosts: all
  vars:
    spark_cluster:
      - name: "spark-ukt0-test"
        flavor: "4x16"
        image: "CentOS7"
        num_nodes: 1
  roles:
    - role: stackhpc.os-shade
      os_shade_venv: "/home/{{ ansible_user }}/os-shade-venv"
    - role: stackhpc.cluster-infra
      cluster_name: "opencb"
      cluster_venv: "/home/{{ ansible_user }}/os-shade-venv"
      cluster_params:
        cluster_prefix: "spark-ukt0"
        cluster_keypair: "usual"
        cluster_net:
          - net: "test"
            subnet: "test"
            security_groups:
              - "default"
        security_groups_set_flag: true
        cluster_groups:
          - "{{ spark_cluster }}"
        # Map cluster_groups to inventory groups
        cluster_roles:
          - name: "rest"
            groups: "{{ spark_cluster }}"
          - name: "daemon"
            groups: "{{ spark_cluster }}"
          - name: "monitoring"
            groups: "{{ spark_cluster }}"
      cluster_group_vars:
        all:
          ansible_user: centos
